### ISSUE TITLE
How do you update models through YAML files?

### ISSUE THREAD

**Issue by adRn-s** [NICHD-BSPC/effort-log#3]
For example, Imagine we had a DB populated with entries, and wanted to add a new PI, or simply add a new project to an existing PI. We could go inside the docker container, edit the corresponding YAML file, And then? what would be your 'workflow'? I think it would go in the lines of: alembic revision, flask migrate, flask upgrade... etc.

Note 1: Since flexibility in the models would be optimal. Have you considered a NoSQL backend? Would this help us into having a constant "live reloading" of YAML files?

Note 2:  I found this [lib](https://github.com/miguelgrinberg/flask-migrate) that seems to have the required workflow automatized. Yet, my experience with Flask is overall rather limited.

Thanks in advance!

**Comment by daler** [comment]
I use `docker compose down && docker compose up --build` which re-makes the docker container. This copies the (possibly-edited) YAML files from the repo into the container. Since the copy step is last in the Dockerfile, everything else is cached already and so it's only a few seconds of down time. I actually run something similar to those commands nightly because I have separate tooling which automatically edits the YAML based on our internal GitLab groups and projects.

The alternative to copying into the container would be to point the app to a mounted location containing the YAMLs, similar to how the sqlite3 db is handled. In that case just editing the YAML would be sufficient for the app to see it, but since it's [read into the config in memory](https://github.com/NICHD-BSPC/effort-log/blob/main/app/config.py#L20) I think you would still need to restart the app to update it.

The app is already using flask-migrate to support future db migrations if the [single, simple model](https://github.com/NICHD-BSPC/effort-log/blob/main/app/app/models.py) is ever updated, but the PIs and projects are intentionally stored *outside* of the db to make this sort of use-case lightweight and not require messing with db migrations.

All that said . . . . this question gave me some ideas. Shouldn't be to bad to hot-reload the YAMLs. I'll work on a PR that addresses this.

**Comment by daler** [comment]
Addressed in #4, let me know how it goes...

**Comment by adRn-s** [comment]
Works like a charm 👍🏽
